- src/adapters/ScatterPlotAdapter.tsx
- src/plots/Histogram.stories.tsx
- src/plots/Histogram.tsx
- src/plots/Pie.stories.tsx
- src/plots/Pie.tsx
- src/plots/PlotlyPlot.tsx
- src/plots/ScatterPlot.stories.tsx
- src/plots/ScatterPlot.tsx
- src/plots/Types.ts
This branch centralizes common code for Plotly based plots into a React Component called `PlotlyPlot`. It also makes use of React Suspect to lazy load the `Plot` component from the plotly package. This means that component will not be loaded into the browser until it is used on the webpage.
> Refactor plotly plot

- src/plots/Boxplot.tsx
- src/stories/Boxplot.stories.tsx
Moving controls outside of the plot component means that the outside has to decide whether or not the control is appropriate to show.
I have put this logic in the storyArgTypes function.
I also now doubt calling many of the props defaultXXXX - that naming assumed that these were the defaults that the user could alter with a plot-internal control widget.
> removed Plotly opacity slider and moved it to storybook controls

- src/stories/api/getMarkersFromFixtureData.tsx
async JSON fetching wasn't working in the github.io deployment due to an absolute path
> actually fixed paths

- src/components/plotControls/HistogramControls.tsx
- src/components/widgets/NumberAndDateInputs.tsx
- src/components/widgets/NumberAndDateRangeInputs.tsx
- src/stories/widgets/DateInput.stories.tsx
- src/stories/widgets/DateRangeInput.stories.tsx
- src/stories/widgets/NumberInput.stories.tsx
- src/stories/widgets/NumberRangeInput.stories.tsx
Input widgets had the ability to be controlled (state managed externally) *or* uncontrolled (state managed internally). This is tricky to get right, and we don't have an immediate need for uncontrolled behavior, so this PR removes that feature.
Additionally, `HistogramControls` no longer requires `selectedRangeBounds` to display the range selection widget. This gives the user a little more flexibility in drawing a selection. The selection is still "snapped" to the left-edge of the left-most selected bin, and the right-edge of the right-most selected bin.
> Remove uncontrolled behavior from date/number related inputs

- src/plots/Histogram.tsx
data.valueType can be undefined which wasn't being handled properly.
For the attention of @moontrip who will find this relevant to https://github.com/VEuPathDB/web-components/issues/66
> Small histogram range selection bug fix

- src/plots/ScatterAndLinePlotGeneral.tsx
- src/stories/plots/ScatterAndLinePlotGeneral.stories.tsx
added three new props to the scatter plot component for visualization: displayLegend, displayLibraryControls, and setMargin. These props are useful for handling the grid view of the scatter plot viz.
> add scatter plot props for corresponding visualization

- src/EntityDiagram/EntityDiagram.tsx
The need for keys in the render method of `CustomNode` can be eliminated by using a React `Fragment`, rather than an array. This requires a change to the `renderNode` prop of `EntityDiagram`.
> Eliminate need for keys in CustomNode

- src/components/plotControls/ScatterplotControls.tsx
- src/hooks/usePlotControls.tsx
- src/stories/plotControls/ScatterplotControls.stories.tsx
Implemented scatter plot controls that would be used at scatter plot viz to change data response (and plot). A story is made to test and usePlotControls hook is changed/utilized for that purpose. With the addition of of the "bestFitLineWithRaw" response, I feel that the "SmoothedMean" may be no longer required, but it is included anyway. A screenshot is attached here.
> making Scatter plot controls

- src/components/plotControls/XYPlotControls.tsx
- src/components/widgets/RadioButtonGroup.tsx
- src/hooks/usePlotControls.tsx
- src/plots/Barplot.tsx
- src/stories/plotControls/XYPlotControls.stories.tsx
- src/stories/plots/Barplot.stories.tsx
- src/stories/widgets/RadioButtonGroup.stories.tsx
This is required for the change from box button to radio button for scatterplot viz. This PR includes several works:
- created radio button group widget with various props and made its story
- changed XYPlotControls with the new widget and its story
- changed useControls with the name of XYPlot
- clean-up barplot and its story
A screenshot is attached:
> new radio widget, stories, changes for controls

- src/plots/Histogram.tsx
- src/plots/PlotlyPlot.tsx
this will address the issue at web-eda, [All visualization plots need static axes (undraggable/unscrollable)](https://github.com/VEuPathDB/web-eda/issues/143)
> add a default prop, fixedrange, at PlotlyPlot

- src/components/plotControls/XYPlotControls.tsx
One of the XYPlotControls option, `SmoothedMean`, is now removed from backend, thus it is also removed at the plot control
Here is a screenshot. Although all options are equally spaced per request by Danica etc., I feel that the space between the `Raw` and `Smoothed Mean With Raw` may be better to be narrowed (or wider), especially without the SmoothedMean option. This may be alleviated with the props, `minWidth`, though
> remove SmoothedMean option in XYPlotControls

- src/components/plotControls/XYPlotControls.tsx
- src/components/widgets/RadioButtonGroup.tsx
- src/stories/plotControls/XYPlotControls.stories.tsx
- src/stories/widgets/RadioButtonGroup.stories.tsx
added a new prop to control radio button item's margin-right prop for possibly better alignment of items. A screenshot is attached where itemMarginRight was set to 50
> adding radio button item's margin-right prop

- src/plots/XYPlot.tsx
- src/stories/plots/XYPlot.stories.tsx
- src/types/general.ts
- src/types/plotly-omissions.ts
examined and tested to add legend title using XYPlot component. If acceptable, then I will add this approach to other plot components. A screenshot with an exemplary title of `legend title example` is attached:
> legend title example at XYPlot component

- src/components/plotControls/AxisRangeControl.tsx
- src/components/widgets/Notification.tsx
- src/components/widgets/NumberAndDateInputs.tsx
- src/components/widgets/NumberAndDateRangeInputs.tsx
- src/plots/Histogram.tsx
- src/stories/plots/Histogram.stories.tsx
- src/stories/widgets/DateInput.stories.tsx
- src/stories/widgets/NumberInput.stories.tsx
- src/stories/widgets/NumberRangeInput.stories.tsx
This is needed for https://github.com/VEuPathDB/web-eda/issues/198 because the histogram usually scales its x-axis to the min/max of the data.  Now you can specify a **wider** range with this prop, but not a narrower one.  This means that all data bins are always shown.  (If you need to zoom in, then provide zoomed data.)
An ugly story is added to both of the SelectedRange stories (number and date) to demo the independentAxisRange control.
> Add independentAxisRange prop to Histogram and custom validators to number/date inputs

- src/components/plotControls/BinWidthControl.tsx
- src/plots/Histogram.tsx
When the date type is `number`, a `ReferenceError` is thrown since `Number` doesn't have the `replace` method.
> only call .replace() on strings

- src/components/widgets/NumberAndDateInputs.tsx
- src/plots/Barplot.tsx
- src/plots/Histogram.tsx
- src/types/plots/addOns.ts
Generalised `dependentAxisLogRange` into an AddOn that works for histogram and barplot.
> Log axis for barplot and log tick number formatting

- src/components/widgets/Button.tsx
- src/components/widgets/Switch.tsx
The previous import was using an implicitly installed package (`@material-ui/styles`). This causes compile issues when _this package_ is used as a dependency.
Instead, we should use `@material-ui/core/styles`, since it is explicitly included in `package.json`.
> Use explicitly installed package import

- src/components/widgets/Button.tsx
- src/components/widgets/NumberAndDateInputs.tsx
- src/components/widgets/NumberAndDateRangeInputs.tsx
Fixes #118 
Goes with EDA PR https://github.com/VEuPathDB/web-eda/pull/270  
118 was basically fixed anyway, but I took the opportunity to fix some offensive styling issues
- reset buttons are less in your face
- x and y axis histogram filter controls now line up vertically
- histogram filter subsetting range control reset button now lines up (on FF at least)
- Histogram/Barplot viz controls are essentially unchanged - they were minimal and inoffensive anyway IMO.
> basic styling changes

- src/plots/Barplot.tsx
- src/plots/Histogram.tsx
Spotted by @moontrip in https://github.com/VEuPathDB/web-eda/pull/254#issuecomment-891205601 
Actually we're not out of the woods yet.
As Dave points out, the mouse-over numbers are also affected by the rounding (now in logscale mode only).  This needs to be addressed through further digging into the Plotly manual.
> Excessive rounding on y-axis tick numbers bugfix

- src/plots/MosaicPlot.tsx
Fixes https://github.com/VEuPathDB/web-components/issues/151
Note the "proportion" text on the left--slightly different than the spec, so I'll take feedback on it. Also, I opted to leave the x-axis labels counts and percentages in place.
> Mosaic minor changes

- src/plots/Barplot.tsx
- src/plots/Boxplot.tsx
- src/plots/Histogram.tsx
- src/plots/PlotlyPlot.tsx
- src/stories/plots/XYPlot.stories.tsx
- src/types/plots/addOns.ts
Fixes https://github.com/VEuPathDB/web-components/issues/127
The color palette works for the following plots:
- Barplot
- Boxplot
- Histogram
- XYPlot
and doesn't work for the following plots:
- Heatmap (not qualitative)
- Mosaic
- Pie
> Add color palette default and prop

- src/components/plotControls/SelectedRangeControl.tsx
- src/components/widgets/NumberAndDateRangeInputs.tsx
- src/plots/Histogram.tsx
- src/stories/plots/Histogram.stories.tsx
Working on a simple Story for "truncated axis" stuff, I found that Histogram had a stupid feature where it wouldn't allow you to zoom in on the x-axis and thus hide some of the data that was given to the component.  I think partly the intention was to avoid chopping off bins (in the x-axis direction).  Histogram (and other plots) will have new truncation warnings to make this clear.
There was also a complicated modification to the first and last bins' `binStart` and `binEnd` for range selection purposes, involving a constraint prop called `selectedRangeBounds`.  People have commented that we don't need to constrain the selected range bounds, and I agree. 
So in this ticket I have
1. modified `SelectedRangeControl` to continue to take the `selectedRangeBounds` prop (for auto-fill purposes, …
> Simplification of Histogram x-axis zooming and range selection fixes

- src/plots/PlotlyPlot.tsx
This PR addressed [the issue at the web-eda, #332](https://github.com/VEuPathDB/web-eda/issues/332)
Tried to wrap lengthy legend title text at first. However it was found that the area of legend title did not allow multiple lines: wrapped texts were overlapped in the single line.
Thus, it was decided to use ellipsis with tooltip. A screenshot is attached as follows:
> legend title ellipsis with tooltip

- src/components/widgets/Notification.tsx
- src/plots/Histogram.tsx
This is for follow-up items regarding truncated axis stuffs: see the [previous PR](https://github.com/VEuPathDB/web-eda/issues/98) and https://github.com/VEuPathDB/web-eda/issues/382. Will also make corresponding PR at web-eda.
I have discussed with Sheena about the appropriateness of new warning icon and she said it looked great.
Also here are additional screenshot for X-axis line (depending on the presence of y-axis range, esp. yMin > 0 or not)
> follow-ups for truncated axis - warning icon, plot line

- src/EntityDiagram/EntityDiagram.tsx
Fixes https://github.com/VEuPathDB/web-eda/issues/388
I opted for removing the defined width from the ED Text component, as it seems with the box layout we're using we'll never want the text to wrap anyway. This should fix the styling for the length of entity names we currently have, but if we get much longer ones in the future, the text will start overflowing the box bounds.
> Remove width prop from ED Text

- src/plots/BirdsEyePlot.tsx
Addresses QA feedback for https://github.com/VEuPathDB/web-eda/issues/234
<s>This is so trivial I'm going to merge it without review.</s>
Update: less trivial fix now.  Inner div now sets focus, outer div cancels it.
Had to use onMouseLeave() for bubbling reasons.  For symmetry I used onMouseEnter() too.
I would appreciate just 1/3 reviews please!
Can be tested in Storybook :-)
> Changed focus behaviour of birds eye plot annotations.

- src/plots/Barplot.tsx
- src/plots/Boxplot.tsx
- src/plots/Histogram.tsx
- src/types/plots/barplot.ts
- src/types/plots/boxplot.ts
- src/types/plots/histogram.ts
These are mostly minor styling changes required to implement https://github.com/VEuPathDB/web-eda/issues/335 
The one possibly contentious change is the 0.999 fudge factor in Histogram.tsx - which was needed so that the right-hand edge of the final no-data histogram bar was drawn properly.
Storybook stories have been checked and hopefully unchanged, visually.  Though there is no story to demo the new borderColor and outlierMarker props.  Bad!
> Viz plot missing data styling

- src/plots/Barplot.tsx
- src/plots/Boxplot.tsx
- src/plots/PlotlyPlot.tsx
- src/utils/axis-tick-label-ellipsis.ts
This is an initial draft PR that works for barplot: here is [the issue at web-eda](https://github.com/VEuPathDB/web-eda/issues/328)
Unlike the initial thought regarding this work, a possible solution I had suggested before turned out to be inappropriate for this task. Thus, switched back to an approach similar to legend/legend title's ellipsis with tooltip. However, the approach did not work for this task directly, so spent quite a long time to figure out the reason. It turned out that the tick label should have pointer-events attribute to activate tooltip.
Initial impression is that this works fine so will try to do the same thing for boxplot and see. Cleanup is not done yet either.
> long independent axis tick label

- src/plots/PlotlyPlot.tsx
This PR will address the issue, [#395 at web-eda](https://github.com/VEuPathDB/web-eda/issues/395)
A long y-axis title is now handled by ellipsis and tooltip. Currently the max number of characters for y-axis title is set to 50 based on eye test 😃 
A screenshot is shown as follows: somehow backend data service seems not to work correctly so no plot is made, however, it is just okay to see the implementation anyway. Just FYI, this was captured using d-falke data service, GEMS1A Case Control study, and Mosaic 2x2 table plot.
> long y-axis title handled by ellipsis and tooltip

- src/plots/Barplot.tsx
- src/plots/Histogram.tsx
Resolves #220 
Resolves #219 
Switched over to `hovermode: 'closest'` and added custom `hoverformat` text and killed two birds with one stone :-)
> Fixed two mouse-over issues for histogram and bar plot

- src/EntityDiagram/EntityDiagram.tsx
- src/EntityDiagram/diagram.css
With web-eda PR [#504](https://github.com/VEuPathDB/web-eda/pull/504), resolves web-eda issue [#428](https://github.com/VEuPathDB/web-eda/issues/428)
This PR adds class name `expanded-diagram` to the entity diagram for easier styling.
> add expanded entity diagram class

- package.json
- yarn.lock
When upgrading plotly.js version at web-eda, I realized that they released a new version, v2.6.0, while our upgraded version was v2.5.1. For matching the version between the two repos, web-components and web-eda, I have made this PR. From my tests, all stories at web-components seem to work fine like v2.5.1.
> matching new version of plotly.js with web-eda

- src/components/widgets/Switch.tsx
Resolves web-eda [#574](https://github.com/VEuPathDB/web-eda/issues/574)
When toggles are disabled, their text will now be in MEDIUM_GRAY. Otherwise, their text will be black.
Also considered making the text a dark gray when enabled, to better match the toggle itself. Would require adding a fourth gray to our collection, so unless we have lots of support to add another gray we can just use black.
> toggle text gray for disabled, else black

- src/plots/FacetedPlot.tsx
- src/stories/plots/PiePlot.stories.tsx
This PR includes changes to make the faceted plot container element scrollable. The changes are pretty minimal.
Some decisions are needed on how to best apply plot-specific container styles. The most viable short-term approach is to set the container styles in the consuming component (i.e., in web-eda visualizations). Once we have a better handle on what the ideal plot-specific container styles are, we can consider creating plot-specific `FacetedPlot` components in this repo.
ETA I used the CSS grid layout for the container element. This is future-looking for when we enable wrapping and multi facet variables.
> Facet container

- src/plots/FacetedPlot.tsx
- src/plots/PlotlyPlot.tsx
- src/stories/plots/PlotlyPlot.stories.tsx
- src/types/guards.ts
- src/types/plots/index.ts
(Relates to https://github.com/VEuPathDB/web-components/issues/241.)
This PR introduces refs for `FacetedPlot`s.
A `FacetedPlot` ref is defined to be an _array_ of the `PlotRef`s for each rendered subplot; in particular, a `FacetedPlot` instance exposes each subplot's `toImage` callback, so that we can create assemble thumbnails from multiple subplots.
**Future work:**
@dmfalke recently suggested that we make plot-specific `FacetedPlot` components (e.g., `FacetedHistogram`) and apply plot-specific styles there; when it comes time to do that work, the `makeFacetedPlotComponent` factory which I introduced here might help.
> Introduce refs for FacetedPlot

- src/components/ContingencyTable.tsx
Fixes #255 
Trivial (only one review needed I think)
Now looks like:
> Added toLocalString() to ContingencyTable number display

- src/plots/FacetedPlot.tsx
- src/types/plots/index.ts
This PR very trivially allows `facet.data = undefined` and when a facet has undefined data, the title is temporarily rendered with a "NO DATA" prefix.
This allows [this EDA ticket](https://github.com/VEuPathDB/web-eda/pull/721) to handle empty facets consistently and reasonably elegantly.
> Empty facet data as undefined - DRAFT for illustration purposes only.

- src/plots/MosaicPlot.tsx
When x-axis ticks are displayed diagonally, it can cause the width of the plot to vary, since plotly factors the amount of space needed by ticks as a part of the total plot dimensions.
**Before**
**After**
closes #257
> Use vertical ticks for mosaic plot

- src/plots/MosaicPlot.tsx
This is to go with an EDA ticket to be mentioned soon.
See screenshots at https://github.com/VEuPathDB/web-eda/issues/715 for more info.
> Mosaic - blank out x axis labels when they have all zero values

- src/plots/BirdsEyePlot.tsx
Fixes https://github.com/VEuPathDB/web-components/issues/263
Something broke in the Plotly upgrade and it seems impossible to fix here.
So disabling it completely and going with an EDA-side solution.
> Disable hover in Birds Eye Plot in favour of EDA-side mouse-over

- src/plots/MosaicPlot.tsx
Works toward https://github.com/VEuPathDB/web-components/issues/265
> Fix bug that allowed the y-axis labels to overflow the plot vertically

- src/components/ContingencyTable.tsx
This PR introduces new `FacetedContingencyTable` styling props for:
1. The container housing the title and contingency table for a single facet (`singleFacetContainerStyles`)
2. The container for the entire "collection" of facets (`facetedContainerStyles`)
For added clarity, `containerStyles` is also renamed to `tableContainerStyles`.
(In particular, we can use `tableContainerStyles` to specify how the data table(s) should be styled, `singleFacetContainerStyles` to specify the layout for a single facet (title + data table), and `facetedContainerStyles` to specify the layout for all the facets.)
> ContingencyTable: introduce singleFacetContainerStyles and facetedContainerStyles props

- src/plots/FacetedPlot.tsx
- src/plots/MosaicPlot.tsx
- src/plots/PlotlyPlot.tsx
- src/stories/plots/Barplot.stories.tsx
- src/types/plots/addOns.ts
Fixes https://github.com/VEuPathDB/web-eda/issues/681
Sorry, I got a little lost in the adjacent work that was done @bobular. Does this reflect what we've discussed surrounding the above ticket?
> Faceting title and empty data

- src/types/plots/xyplot.ts
While making a R-square table for Scatter plot with the plot options of Best fit with raw ([#694 at web-eda](https://github.com/VEuPathDB/web-eda/issues/694)), it was necessary to add a prop to have R-square value.
> add R-square prop to Scatter plot

- package.json
- src/components/ContingencyTable.tsx
- src/plots/FacetedPlot.tsx
- src/plots/MosaicPlot.tsx
- src/plots/PiePlot.tsx
- src/plots/PlotlyPlot.tsx
- src/plots/facetedPlots/FacetedBarplot.tsx
- src/plots/facetedPlots/FacetedBoxplot.tsx
- src/plots/facetedPlots/FacetedHeatmap.tsx
- src/plots/facetedPlots/FacetedHistogram.tsx
- src/plots/facetedPlots/FacetedMosaicPlot.tsx
- src/plots/facetedPlots/FacetedPiePlot.tsx
- src/plots/facetedPlots/FacetedXYPlot.tsx
- src/stories/plots/Barplot.stories.tsx
- src/stories/plots/Boxplot.stories.tsx
- src/stories/plots/Heatmap.stories.tsx
- src/stories/plots/Histogram.stories.tsx
- src/stories/plots/MosaicPlot.stories.tsx
- src/stories/plots/PiePlot.stories.tsx
- src/stories/plots/XYPlot.stories.tsx
- src/types/plots/index.ts
- src/types/plots/mosaicPlot.ts
- yarn.lock
Works toward https://github.com/VEuPathDB/web-components/issues/259
> Faceting #259

- src/plots/FacetedPlot.tsx
The histogram modals were reverting to `barLayout: undefined` and so were reverting to overlay mode (they should be 'stacked').  This made me realise that other props weren't being passed to the modal, such as log scale.  This fixes that.  Small fix on the EDA-side to remove some redundancy and upgrade to this version when merged.
Not putting this (and EDA sibling) ticket in the project board ticket cycle.
Small facet plot:
Modal:
> Pass all componentProps to faceted modal

- src/components/ContingencyTable.tsx
Works toward https://github.com/VEuPathDB/web-eda/issues/761
I also right-aligned the column labels that sit above right-aligned numbers. The variable coverage table will be handled in web-eda.
Interestingly, I believe the numbers in this font are equal-width, even though the font's letters are not. I didn't realize some fonts did that. Neat!
> Right align table numbers

- src/components/plotControls/PlotLegend.tsx
- src/stories/plotControls/PlotLegend.stories.tsx
This PR will address the following works:
a) changing checkbox color into grayish - discussed at [#765](https://github.com/VEuPathDB/web-eda/issues/765)
b) making legend label clickable to select/unselect checkbox #271 
c) considering scrollbar when the number of legend list is large: currently set to the height of Scatter plot's R-square table (story is added)
d) several changes for better display
Here is an example screenshot of a faceted plot with R-square table:
> several custom legend works

- package.json
- src/plots/Boxplot.tsx
Works toward https://github.com/VEuPathDB/web-components/issues/264
Thankfully the option I needed to change was commented describing this exact behavior :)
Note that the empty space leftover will disappear even if there is just empty data for the series in question, rather than the series being set to invisible, but that the series' legend entry will remain (this appears to be different than in barplot, where the series legend entry disappears for empty data).
> Remove boxplot empty gap

- package.json
- src/components/plotControls/PlotLegend.tsx
This resolves https://github.com/VEuPathDB/EdaNewIssues/issues/202, which allow the case of single overlay data for displaying legend: previously single data is not allowed to show legend.
After sleeping on it, I thought that the simplest case is to add a prop to allow displaying legend, in conjunction with the pre-existing condition to check the data.length > 1 (this is for the case without overlay).
By doing this, a condition to check the presence of vizConfig.overlayVariable will allow to show legend for overlayVariable regardless of its length - will make a PR regarding this at web-eda soon
Here is a screenshot, with the same example used in the issue.
> add a prop to allow displaying legend

- package.json
- src/map/config/map.ts
- src/stories/AnimatedMarkers.stories.tsx
- src/stories/ChartMarkers.stories.tsx
- src/stories/DonutMarkers.stories.tsx
- src/stories/Map.stories.tsx
- src/stories/MultipleWorlds.stories.tsx
- src/stories/SidebarResize.stories.tsx
- src/stories/api/getMarkersFromFixtureData.tsx
Resolves #324.
I have left the old `map.json` in place, so as to avoid making a breaking change. We should remove `map.json` in the next major release of `@veupathdb/web-components`.
> Introduce TypeScript-based map config (resolves #324)

- package.json
- src/components/widgets/RadioButtonGroup.tsx
- src/map/ChartMarker.tsx
- src/stories/api/getMarkersFromFixtureData.tsx
- src/stories/widgets/RadioButtonGroup.stories.tsx
- src/types/plots/barplot.ts
The enlarged popups for ChartMarkers now use Barplot instead of Histogram. 
Also allowed an array of colors (per series) to be passed to Barplot. This should not affect regular barplots.
Also added optionLabels to RadioButtonGroup - I added a Story for this but was unable to get Storybook running on my laptop (white browser window - no errors in the terminal (forgot to check the FF console)).
> Switch chart markers to use barplot; add display labels to RadioButtonGroup

- package.json
- src/EntityDiagram/EntityDiagram.stories.tsx
- src/EntityDiagram/EntityDiagram.tsx
Addresses issue #326
Current code is hardcoded to only render repeated measures as a 1:many relationship. I will update when backend includes the necessary fields/properties.
The current implementation looks as follows:
**Amazonia ICEMR Brazil Cohor**
**GEMS1 Case Control**
> Update entity diagram UI to represent 1:1 and 1:many relationships

- package.json
- src/components/widgets/LabelledGroup.tsx
- src/components/widgets/NumberAndDateInputs.tsx
- src/components/widgets/NumberAndDateRangeInputs.tsx
- src/components/widgets/RadioButtonGroup.tsx
- src/types/plots/scatterplot.ts
This is related to a web-eda PR, https://github.com/VEuPathDB/web-eda/pull/1032
The purpose of this work is to have an additional prop, which will be used to examine whether the data has no smoothed mean and use the info to show/hide message.
There is another minor request involved in this PR, which is to increase the title of axis range control, e.g., Y-axis controls to be the same same font and size as the text for "Axis variables" and "Stratification variables". https://github.com/VEuPathDB/web-eda/issues/1011#issuecomment-1097035678 and https://github.com/VEuPathDB/web-eda/issues/1011#issuecomment-1097045514
> add a prop for handling no smoothing at scatter Viz

- package.json
- src/plots/ScatterPlot.tsx
- src/types/plots/addOns.ts
This makes log scale controls for both X and Y axes in the Scatter plot and its corresponding Viz. https://github.com/VEuPathDB/EdaNewIssues/issues/292
Since Scatter plot (and Viz) allow date variable at X and Y axes, it is configured to disable the log scale control when the selected variable is date type.
Here are example screenshots with explanation in the title: the same study and variables with the screenshot in the ticket were used for a comparison purpose.
- log scale is on for X-axis
- controlling legend to show/hide data: this may be useful for scattered data that show large range of confidence intervals in Y-axis.
- A demo to show that log scale control at the Y-axis is disabled because its variable type is date
> making log scales for both X and Y in the Scatter plot

- package.json
- src/plots/ScatterPlot.tsx
- src/utils/extended-axis-range-truncations.ts
This addresses a suggestion, https://github.com/VEuPathDB/web-eda/issues/1153#issuecomment-1142637556, which needs to increase margin for scatterplot log scale
After testing several cases, one of the simplest solution is to increase the margin when log scale is used. Screenshot is added for a comparison with Danica's screenshot at the comment above. As shown, marker is not cut in this implementation.
Note that this is only applied to max range of dependent axis because it would be most likely the case we need to consider.
> adding increased margin for scatterplot log scale

- package.json
- src/map/SemanticMarkers.tsx
Resolves #362 
I have tested this and it solves the 1 second exception, and changing `updateBounds()` to `debouncedUpdateBounds()`  doesn't cause any noticeable delay or increase the number of back-end requests.
@jernestmyers @moontrip and @chowington may be interested to see this small change (though I think I originally wrote the buggy code)
> Map component: cancel debounce and use the debounced version for the 'one off' call too

- package.json
- src/plots/BirdsEyePlot.tsx
Works to resolve [this issue in `web-eda`](https://github.com/VEuPathDB/web-eda/issues/994) and is supplemental to the work in [this PR](https://github.com/VEuPathDB/web-eda/pull/1260).
> Change BirdsEye bgColor to match VarCompleteness

- src/map/MapVEuMap.tsx
- src/stories/Map.stories.tsx
This draft PR is for @dmfalke 😄 (branched out from react-leaflet-v3-ref (https://github.com/VEuPathDB/web-components/pull/347), testing sharedPlotCreation used in PlotlyPlot component, but did not work for me.
I know that Dave changed package.json to allow react-leaflet v3 but somehow it did not work for me. Thus I am still using npm-pack-here to work with MapViz at web-eda.
Note that I left console.logs to check the change of mapRef (map ref). From my observation, even without implementing sharedPlotCreation, mapRef inside useImperativeHandle does not change for initial map (mapRef inside = null) load even if outside mapRef is changed before using useImperativeHandle.
> testing sharedPlotCreation for react-leaflet v3

- package.json
- src/components/plotControls/AxisRangeControl.tsx
- src/map/ChartMarker.tsx
- src/plots/Barplot.tsx
- src/plots/Histogram.tsx
- src/plots/LinePlot.tsx
- src/plots/ScatterPlot.tsx
- src/stories/ChartMarkers.stories.tsx
- src/stories/api/getMarkersFromFixtureData.tsx
- src/types/guards.ts
- src/utils/extended-axis-range-truncations.ts
- src/utils/logscale-dtick.ts
- src/utils/truncation-layout-shapes.ts
- yarn.lock
This is branched out from https://github.com/VEuPathDB/web-components/pull/363 to address two things for scatter and line plots:
a) set log scale range correctly
b) truncation
This is related to the web-eda PR, https://github.com/VEuPathDB/web-eda/pull/1241
To reviewers, @bobular & @asizemore: 
As mentioned above, I have branched out from https://github.com/VEuPathDB/web-components/pull/363 to address the two tasks. I have separated them because this one would have taken some time while you were reviewing the previous PR. 
Now, you can review this PR instead of https://github.com/VEuPathDB/web-eda/pull/1241.
> Viz log range truncation

- package.json
- src/components/plotControls/PlotLegend.tsx
This will address https://github.com/VEuPathDB/web-components/issues/344
Done based on several comments by Bob and Dave in the ticket
For reference, a screenshot is attached in the following:
> changing legend styles

- package.json
- src/map/ChartMarker.tsx
This draft PR is branched out from https://github.com/VEuPathDB/web-components/pull/371 as this needs map's log scale functionality
This is a temporary solution, just minimizing gap between small and large (using mouse tool) charts: Please see this comment for more detailed info: https://github.com/VEuPathDB/web-components/issues/380#issuecomment-1203128901.
> addressing SVG log scale

- package.json
- src/map/ChartMarker.tsx
Resolves #386 
The current implementation uses the `Total: <insert count>` string as a default value for the independent axis, like so:
```js
independentAxisLabel={
props.independentAxisLabel ?? `Total: ${sumValuesString}`
}
```
I've removed the option to render the passed-in `props.independentAxisLabel` to only render the default string. The result is as shown.
> Use existing default string for x-axis label in ChartMarker popover plot

- package.json
- src/types/plots/addOns.ts
This will possibly address https://github.com/VEuPathDB/web-eda/issues/1200. The easiest solution is to change the order of colors defined in SequentialGradientColorscale: alternatively, one may adjust array index at mapViz but in this PR, the former is used.
The change of color order at legend means that the bar colors should also be changed. Here is an example screenshot to show.
(did not clean up the PR yet but will do it later)
> changing color for map continuous overlay

- package.json
- src/plots/Barplot.tsx
- src/plots/Histogram.tsx
- src/plots/LinePlot.tsx
- src/plots/ScatterPlot.tsx
- src/stories/plots/LinePlot.stories.tsx
- src/utils/tick-settings.ts
This will address https://github.com/VEuPathDB/web-eda/issues/1275
I have added the power format for Viz/axis who has log scale control such as Histogram Y-axis, barplot Y-axis, Scatterplot X and Y axes, and Lineplot X and Y axes.
For Histogram and Barplot, it was found that they had tickformat attribute that formats large number, so it is removed to show power format. 
Just for an information, Plotly.js actually supports minexponent attribute which controls the starting point of power format display. However, @types/plotly.js somehow do not have type for that. I saw that Danica wanted to show power format from five-figure (e.g., 10^4), which is the default value of minexponent (minexponent: 3), thus I did not consider typing for that: honestly, I could not find a way to extend type to …
> power format of axis label

- package.json
- src/plots/PlotlyPlot.tsx
- src/stories/plots/LinePlot.stories.tsx
- src/utils/removeHtmlTags.ts
This PR is related to https://github.com/VEuPathDB/web-eda/issues/1433
I figured it out that dependent axis label can take html tags like `<b>, <i>, <br>`, however, its tooltip, which is actually SVG text attribute, still shows such tags as string. Thus, it is necessary to remove tags for tooltip string.
I also made a story to test this, as shown in the following screenshot. Those tags are not shown in the tooltip.
> handling html tags at y-axis label tooltip

- package.json
- src/components/plotControls/PlotGradientLegend.tsx
- src/components/plotControls/PlotLegend.tsx
- src/components/plotControls/PlotListLegend.tsx
- src/stories/plotControls/PlotLegend.stories.tsx
Works toward https://github.com/VEuPathDB/web-eda/issues/1399 and https://github.com/VEuPathDB/web-eda/issues/306
> Refactor legend to incorporate gradient legend

- package.json
- src/plots/Histogram.tsx
Resolves https://github.com/VEuPathDB/web-eda/issues/872
I decided to keep this on the web-components side, and only make changes to the axis configuration when there are a tiny number of bins (<= 4).  If we need to adjust the threshold (or the approach) after testing in the wild, that's fine. I just wanted to tread as lightly as possible to avoid unintended consequences.
> Avoid extra bin labels

- package.json
- src/components/widgets/NumberAndDateInputs.tsx
Resolves https://github.com/VEuPathDB/web-eda/issues/872
Solves the issue where the numeric bin width slider input is outlined red when at an allowed lower or upper limit.
Adjusting the bin width to the min or max was only possible with the slider, not the number input.
> Fix red warning for bin width at limit of range

- package.json
- src/plots/MosaicPlot.tsx
This will address https://github.com/VEuPathDB/web-eda/issues/1435
Initially, more complicated approach was used to address this issue by changing PlotlyPlot component, however, it was found that there was much simpler way. 
Here is a screenshot using the same example case in the ticket:
> change the order of Mosaic color

- package.json
- src/plots/Boxplot.tsx
This will address https://github.com/VEuPathDB/web-eda/issues/1472
Realized that we already had a padding function for other plots such as scatterplot and lineplot, so the same is used for this boxplot.
For the same example shown in the original ticket, adding a padding would look like below:
> add padding for boxplot markers

- package.json
- src/components/plotControls/PlotListLegend.tsx
This will resolve https://github.com/VEuPathDB/web-eda/issues/1602. Tested extensively with web-eda Vizs and all seem to work fine. 
Here are example screenshots with a Scatterplot Viz.
- using qa-restricted (unchecked legend item turns to be gray)
- using dev with current PR (unchecked legend item remains the same color, not being gray)
> no gray for legend when unchecked

- package.json
- src/types/plots/lineplot.ts
- yarn.lock
This is to define a type for a new lineplot prop, which will be used for https://github.com/VEuPathDB/web-eda/issues/1519.
> add a lineplot prop to enable connecting points

- package.json
- src/components/plotControls/PlotGradientLegend.tsx
This is related to https://github.com/VEuPathDB/web-components/issues/454. 
While I was working on the colormap range, I noticed that the decimal points in the colormap's tick labels were often too long, so I have set it up to be 2 decimal points. Following is an example based on storybook.
a) without setting decimal points
b) two digit decimal points
> set decimal points for colormap ticks
