src/plots/Histogram.stories.tsx
src/plots/Pie.tsx

I know this isn't the **real** histogram plot compoinent, but I just wanted to check that 'bar' plots would do the job for more typical histogram data, and that the bars would be side-by-side in the multi-variate example.
I also fixed a typo in Pie.tsx

more real-life histogram examples

---

.storybook/main.js
docs/GETTING_STARTED.md
package.json
src/plots/PlotlyPlot.tsx
yarn.lock

This PR contains documentation for getting started with developing in this repo. It also adds the [docs](https://github.com/storybookjs/storybook/tree/master/addons/docs) and [viewport](https://github.com/storybookjs/storybook/tree/master/addons/viewport) storybook addons.
Note that there is an issue with the docs addon where it doesn't document props inherited from an extended interface: https://github.com/strothj/react-docgen-typescript-loader/issues/47. The effect this has on this repo is that props defined in `PlotComponentProps` do not appear in the **Docs** tabs. Hopefully this will be addressed at some point, or we will want to find another way to make those props appear.

Getting started

---

src/plots/ScatterPlot.stories.tsx

This PR contains improved sample data for the scatter plot stories.

Better scatterplot sample data

---

src/plots/ScatterAndLinePlot.stories.tsx
src/plots/ScatterAndLinePlot.tsx

add new scatter and line plot.

Scatter and Line plot dev#1

---

src/plots/Heatmap.tsx
src/stories/Heatmap.stories.tsx
src/stories/ScatterAndLinePlotGeneral.stories.tsx

Initial heatmaps
https://redmine.apidb.org/issues/42052

[DK] first heatmaps

---

src/plots/Heatmap.tsx
src/stories/Heatmap.stories.tsx

Comments are made at the ticket:
https://redmine.apidb.org/issues/42052

[DK] heatmap with Control & change props

---

src/components/plotControls/HistogramControls.tsx

Uses presence or absence of callback to determine if a control should be displayed.

Make histogram controls optional

---

src/map/LegendListRadioButton.tsx
src/map/MapVEuLegendSampleList.tsx
src/stories/ChartMarkers.stories.tsx
src/stories/api/getMarkersFromFixtureData.tsx

This is for the ticket, [Histogram: rename yAxisRange prop to dependentAxisRange and make it NumberRange type](https://github.com/VEuPathDB/web-components/issues/61). Renamed to dependentAxisRange and made it to NumberRange type.

[issues-61] rename yAxisRange prop to dependentAxisRange etc

---

package.json
src/EntityDiagram/EntityDiagram.stories.tsx

Primary change is adding the `component` property to the Meta descriptor. Not sure this will work, but worth a shot.

Fix entity diagram story

---

src/components/widgets/PopoverButton.tsx
src/plots/Histogram.tsx
src/stories/plots/Histogram.stories.tsx

* Remove ripple effect from `PopoverButton`
* Allow CSS length string to be used for height/width of Histogram

Small changes

---

src/components/widgets/NumberAndDateInputs.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/components/widgets/Slider.tsx
src/stories/widgets/DateInput.stories.tsx
src/stories/widgets/DateRangeInput.stories.tsx
src/stories/widgets/NumberInput.stories.tsx
src/stories/widgets/NumberRangeInput.stories.tsx
src/stories/widgets/Slider.stories.tsx

Just realised I spelled auxiliary wrong in the story file...
I made the draft PR to make it easier to discuss a change that @dmfalke made that seemed to have broken all number/date text input fields.  I'll make a specific comment below.

Slider with auxiliary text input

---

src/EntityDiagram/EntityDiagram.stories.tsx
src/EntityDiagram/EntityDiagram.tsx

This PR introduces some changes to the look of the entity diagram:
* Text is centered vertically using the `vertical-anchor` attribute
* In expanded mode, shading is a small strip at the bottom of the node.

Entity diagram touchup

---

src/EntityDiagram/EntityDiagram.tsx

1. Add border radius to boxes
2. Add space between arrows for expanded mode
3. Soften arrow colors
4. Change how highlighted border is rendered.

Several updates

---

src/plots/ScatterAndLinePlotGeneral.tsx
src/stories/plots/ScatterAndLinePlotGeneral.stories.tsx

Some changes are made for visualization. Opacity slider is removed, some props are adjusted, etc.

changing scatter plot component for viz

---

src/components/widgets/NumberAndDateInputs.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/hooks/usePlotControls.tsx
src/plots/Histogram.tsx
src/stories/api/githubDates.ts
src/stories/widgets/DateInput.stories.tsx
src/stories/widgets/DateRangeInput.stories.tsx
src/types/general.ts
src/types/guards.ts
src/types/plots/histogram.ts

This is going to make io-ts validation of saved UI state much easier...

Change handling of dates from Date to string

---

src/EntityDiagram/EntityDiagram.tsx
src/components/plotControls/HistogramControls.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/components/widgets/Slider.tsx
src/hooks/usePlotControls.tsx
src/plots/Histogram.tsx
src/stories/api/githubDates.ts
src/stories/plotControls/HistogramControls.stories.tsx
src/stories/plots/Histogram.stories.tsx
src/stories/widgets/NumberRangeInput.stories.tsx
src/types/general.ts
src/types/guards.ts
src/types/plots/histogram.ts

To do:
- Disable some plotly interaction e.g. axis panning.
- add prop to disable mouseover tooltips

Tweaks for adding full histogram controls to EDA

---

src/components/plotControls/HistogramControls.tsx
src/components/widgets/LabelledGroup.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/plots/Histogram.tsx

Associated EDA PR https://github.com/VEuPathDB/web-eda/pull/84 
Fixes #117 
Raised a possible back end issue
https://github.com/VEuPathDB/EdaDataService/issues/31

Selected Range and x-axis zoom interaction fixes

---

src/components/plotControls/HistogramControls.tsx
src/components/widgets/Slider.tsx
src/plots/Histogram.tsx
src/plots/MosaicPlot.tsx
src/stories/plots/Histogram.stories.tsx
src/stories/plots/MosaicPlot.stories.tsx
src/stories/widgets/Slider.stories.tsx

Some plots (at least Histogram) were throwing errors.  I'll fix all the plots promised for the demo
- histo (done)
- mosaic (done)
- scatter (DK to do please)
- bar (DK to do)

Make Histogram and Mosaic plots display empty axes when given empty data

---

src/EntityDiagram/EntityDiagram.stories.tsx
src/EntityDiagram/EntityDiagram.tsx

This PR includes support for adding counts and a filter icon to entity nodes.

Entity diagram counts and highlighting

---

src/EntityDiagram/EntityDiagram.tsx

Update font styling in EntityDiagram

---

src/EntityDiagram/EntityDiagram.tsx

I decided to increase the font weight a bit

Increase font weight

---

src/components/plotControls/HistogramControls.tsx
src/components/plotControls/XYPlotControls.tsx
src/components/widgets/LabelledGroup.tsx
src/components/widgets/RadioButtonGroup.tsx

Removed the border and title for the histogram, made the scatterplot controls look like the histogram ones

Cosmetic fixes to histogram and scatterplot controls

---

src/EntityDiagram/EntityDiagram.tsx

Fixes https://github.com/VEuPathDB/web-components/issues/110

Entity diagram tidy

---

src/components/widgets/Tooltip.tsx

Add a tooltip widget module, along with a fancy `HtmlTooltip` component.

Add tooltip module

---

src/components/widgets/Slider.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/203

Fallbacks for slider to avoid uncontrolled/controlled inputs warning

---

src/plots/Histogram.tsx

This allows us to handle two types of binEnd for dates - see https://github.com/VEuPathDB/EdaDataService/issues/54

Histogram: add adjustBinEndToEndOfDay prop

---

package.json
src/plots/Boxplot.tsx
src/plots/Histogram.tsx
src/stories/plots/Boxplot.stories.tsx
yarn.lock

Sorry this is a mixed PR.
Couldn't wait for the pure TS upgrade to be approved before continuing work on the boxplots.

TS and SB upgrades and Boxplot fixes for missing/empty data

---

src/plots/XYPlot.tsx

Trivial hovermode fix

---

src/plots/MosaicPlot.tsx
src/stories/plots/MosaicPlot.stories.tsx

- Swap percent and raw value positions in hover labels
- Remove percents and raw values from x-axis labels
- Fix bug where x-axis labels were showing even when
showColumnLabels was false
Edit for related tickets:
- https://github.com/VEuPathDB/web-components/issues/181
- https://github.com/VEuPathDB/web-components/issues/182

Various mosaic label changes

---

src/types/plots/addOns.ts

@dmfalke here is the change to have ColorPaletteDark at addOns.ts as we discussed.

define ColorPaletteDark at addOns

---

src/plots/PlotlyPlot.tsx

This addresses the issue described in [this comment](https://github.com/VEuPathDB/web-eda/issues/272#issuecomment-912747198).

Ensure toImage is called after plot is initialized

---

src/plots/MosaicPlot.tsx

This handles long axis tick label with ellipsis and tooltip for Mosaic plot as discussed in #211 PR. Here is a screenshot.

handling long tick label for Mosaic plot

---

src/plots/Histogram.tsx

Added extra props to control bin start/end inclusive/exclusive for correct independent axis range setting, fixed some missing dependencies in truncation shading

Extra props to control histogram independent axis range setting from bin starts and ends

---

src/components/widgets/Button.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/components/widgets/Switch.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/330
In addition to changing switch coloring, also decapitalizes button text in general.

Change Switch style

---

src/stories/plots/BirdsEyePlot.stories.tsx

This is just storybook work.
Added an example that shows the popup being clipped.
Played around with width and plotly margins.
Can be fixed in EDA without this code, but we should merge at some point!

Birds eye popup placement explorations

---

src/plots/FacetedPlot.tsx
src/plots/PiePlot.tsx
src/plots/PlotlyPlot.tsx
src/stories/plots/PiePlot.stories.tsx
src/types/guards.ts
src/types/plots/index.ts

Here is a `web-components`-only approach to implementing faceting that I would like feedback and suggestions for
Check out the last two stories in PiePlot.stories.tsx to see how faceted data looks (very simple version for now)

Faceted plot implementation proposal

---

src/plots/BirdsEyePlot.tsx

Was simple in the end!
Please merge into your branch when you've had a look at this.

Fix birds eye plot for the custom legend world

---

src/plots/MosaicPlot.tsx
src/plots/PlotlyPlot.tsx

Bit of a messy PR due to having to calculate lots of stuff plotly doesn't tell you easily.
Requires Plotly 2.x, so blocked by https://github.com/VEuPathDB/web-components/pull/233
Works toward https://github.com/VEuPathDB/web-components/issues/184

Mosaic left legend

---

package.json
src/components/plotControls/PlotLegend.tsx
src/plots/FacetedPlot.tsx
src/plots/PlotlyPlot.tsx
src/stories/plotControls/PlotLegend.stories.tsx
src/types/plots/barplot.ts
src/types/plots/xyplot.ts

@bobular @dmfalke I have made PR for initial custom legend works presented at the dev call. Will make corresponding PR at web-eda

custom legend work

---

src/components/ContingencyTable.tsx

Probably doesn't need three reviews, but you all have skin in the game.
More than happy to have someone style it nicer.
I added `<Spinner />` functionality to the table tab to make transitions between variable selections nicer.

Contingency tables now handle faceted data

---

package.json
src/components/plotControls/PlotLegend.tsx
src/types/plots/boxplot.ts
yarn.lock

This PR will address custom legend markers, colors, etc. for corresponding Vizs.

Custom legend markers and colors

---

src/plots/Histogram.tsx
src/plots/PlotlyPlot.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/595

Make histogram axes lines lighter

---

package.json
src/plots/FacetedPlot.tsx

Remove div container since it interferes with scrolling
closes #240

Faceted plot 2

---

src/components/plotControls/PlotLegend.tsx
src/types/plots/xyplot.ts

made possible legend markers for scatter plot Viz. More detailed adjustments (size etc.) are probably required when adding the custom legend to the Scatter plot with faceted plot.

add possible legend markers for scatter plot Viz

---

src/plots/MosaicPlot.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/703

Make mosaic ignore displayLegend prop

---

src/plots/FacetedPlot.tsx
src/plots/MosaicPlot.tsx
src/plots/facetedPlots/FacetedBarplot.tsx
src/plots/facetedPlots/FacetedHeatmap.tsx
src/plots/facetedPlots/FacetedPiePlot.tsx

Works toward https://github.com/VEuPathDB/web-components/issues/259

Faceted plot variants

---

package.json

forgot to change version for merged custom-legend-works, #279

Bump version for custom-legend-works

---

dist/css/map_styles.css
package.json
src/map/CustomGridLayer.tsx
src/map/MapVEuMap.tsx
src/map/MapVEuMapSidebar.tsx
src/map/MouseTools.tsx
src/map/SemanticMarkers.tsx
src/map/config/map.json
src/map/utils/leaflet-geohash.ts
src/stories/AnimatedMarkers.stories.tsx
src/stories/ChartMarkers.stories.tsx
src/stories/DonutMarkers.stories.tsx
src/stories/MultipleWorlds.stories.tsx
src/stories/SidebarResize.stories.tsx
src/stories/api/getMarkersFromFixtureData.tsx

Progress so far
- commented out the problematic CSS imports.  Need a better solution please anyone!
- named the handlers for bounds (top/bottom/left/right) and viewports (center lat/lon and zoom level) more consistently

Map and CSS tweaks to enable use in EDA

---

package.json
src/map/MapVEuMap.tsx
src/plots/PlotlyPlot.tsx
src/stories/ChartMarkers.stories.tsx
src/stories/DonutMarkers.stories.tsx
src/stories/SidebarResize.stories.tsx
yarn.lock

Works toward https://github.com/VEuPathDB/web-eda/issues/784
Should be used with https://github.com/VEuPathDB/web-eda/pull/812
What's our current protocol for semantic versioning? I bumped this up a minor version because in my mind it's a new feature, but I don't know how we're currently doing things or how they generally work in 0.x semver land. UPDATE: changed to only bump the patch version in accordance with the semver discussion at the dev meeting.

Map viz thumbnail work

---

package.json
src/map/MapVEuMap.tsx

Works toward https://github.com/VEuPathDB/web-components/issues/295

Map base layer prop

---

package.json
src/map/MapVEuMap.tsx

This PR will possibly resolve the issues [#840](https://github.com/VEuPathDB/web-eda/issues/840)
I think this would work, however, since UMSP data is not available, I could not test. Thus, I made this as a draft PR for the time being.

fix map layer issues

---

package.json
src/map/MapVEuMap.tsx

Works toward https://github.com/VEuPathDB/web-eda/pull/837

Add flyToMarkers prop and logic

---

package.json
src/components/NoDataOverlay.tsx
src/components/Spinner.tsx
src/map/MapVEuMap.tsx
src/plots/PlotlyPlot.tsx
src/stories/Map.stories.tsx

Works toward https://github.com/VEuPathDB/web-components/issues/297

Add spinner and no data overlay props to map

---

package.json
src/utils/truncation-layout-shapes.ts

This will resolve #305 . Since Danica assigned this as b56, I added Dave and Jamie as a reviewer for a quick review 😃 Due to time difference, Bob is not included here, hoping this PR is merged tonight. Will merge this when one of you would approve :)
Will make a PR at web-eda to change message (from light gray to medium yellow) soon
Screenshot is attached.

changing truncation color to medium yellow

---

package.json
src/components/plotControls/SelectedRangeControl.tsx
src/map/DonutMarker.tsx
src/map/MapVEuMapSidebar.tsx
src/map/SemanticMarkers.tsx

Also related to [this issue](https://github.com/VEuPathDB/web-eda/issues/585).
Last bit of console log clean up for now.

Clean up console logs

---

package.json

I am SO SO SORRY!!!!!
Version update for too-hastily-merged https://github.com/VEuPathDB/web-components/pull/289

v0.11.22 forgotten version up for lineplot PR #289

---

package.json
src/map/BoundsDriftMarker.tsx
src/map/MapVEuMap.tsx
src/stories/Map.stories.tsx

Works toward https://github.com/VEuPathDB/web-components/issues/321

Fix popup reorientation

---

package.json
src/components/plotControls/AxisRangeControl.tsx
src/components/widgets/Button.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/plots/LinePlot.tsx
yarn.lock

This PR will be used for addressing additional lineplot works. Thus branched out from `lineplot-tooltips` branch. Probably, more commits would be made in this PR in the near future.

additional lineplot works

---

package.json
src/plots/Histogram.tsx

Improve handling of date variables in blue selection range of histograms

---

package.json
src/map/MapVEuMap.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/967

Add maxZoom to a couple of layers

---

package.json
src/components/plotControls/BinWidthControl.tsx
src/components/widgets/NumberAndDateInputs.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/components/widgets/Slider.tsx

This PR related to https://github.com/VEuPathDB/web-eda/issues/1011
Danica asked me to change control's text colors into black, not light gray.

changing control text color to black

---

package.json
src/components/widgets/Tooltip.tsx

Relates to [this issue](https://github.com/VEuPathDB/web-eda/issues/984).
These changes are accompanied by these PRs:
- [WDKClient](https://github.com/VEuPathDB/WDKClient/pull/195)
- [EbrcWebsiteCommon](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/112)
- [ApiCommonWebsite](https://github.com/VEuPathDB/ApiCommonWebsite/pull/47)

Export HtmlTooltip as Tooltip

---

package.json
src/plots/Barplot.tsx
src/plots/Boxplot.tsx
src/plots/Histogram.tsx
src/utils/extended-axis-range-truncations.ts

This will address https://github.com/VEuPathDB/web-eda/issues/1015 with corresponding web-eda PR, https://github.com/VEuPathDB/web-eda/pull/1102

changing padding truncation logic

---

package.json
src/map/SemanticMarkers.tsx

Resolves #352 
Doesn't need two reviewers but thought you both might be interested.

Ensure east-west bounds are slightly different when fully zoomed out

---

package.json
src/plots/FacetedPlot.tsx
src/plots/facetedPlots/FacetedBarplot.tsx
src/plots/facetedPlots/FacetedBoxplot.tsx
src/plots/facetedPlots/FacetedHeatmap.tsx
src/plots/facetedPlots/FacetedHistogram.tsx
src/plots/facetedPlots/FacetedLinePlot.tsx
src/plots/facetedPlots/FacetedMosaicPlot.tsx
src/plots/facetedPlots/FacetedPiePlot.tsx
src/plots/facetedPlots/FacetedScatterPlot.tsx

Resolves [this issue](https://github.com/VEuPathDB/EdaNewIssues/issues/356).
Added a guard to ensure the modal isn't rendered at an inappropriate time- which was the root of the bug that Bob discovered. Also tweaked the styles as shown in the issue's comments.

Address modal bug and tweak styling in faceted plots

---

package.json
src/map/MapVEuMap.tsx
src/map/MouseTools.tsx
src/stories/ChartMarkers.stories.tsx
src/stories/DonutMarkers.stories.tsx
src/stories/Map.stories.tsx

This addresses https://github.com/VEuPathDB/web-eda/issues/971 with corresponding web-eda PR, https://github.com/VEuPathDB/web-eda/pull/1141.
Map related stories are updated as well.

remembering the selection of mouse tool

---

package.json
src/components/plotControls/PlotLegend.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/1347

Add container styles prop to plot legend

---

package.json
src/components/plotControls/BinWidthControl.tsx
src/components/plotControls/HistogramControls.tsx
src/components/widgets/LabelledGroup.tsx
src/components/widgets/NumberAndDateInputs.tsx
src/components/widgets/NumberAndDateRangeInputs.tsx
src/components/widgets/RadioButtonGroup.tsx
src/constants/colors.ts
src/stories/ChartMarkers.stories.tsx
src/stories/plots/LinePlot.stories.tsx
yarn.lock

Works towards https://github.com/VEuPathDB/EdaNewIssues/issues/456

Unify plot controls styling and verbiage

---

package.json
src/components/ContingencyTable.tsx
src/constants/colors.ts

Supports https://github.com/VEuPathDB/web-eda/pull/1470 in resolving https://github.com/VEuPathDB/web-eda/issues/1382

Adjust ContingencyTable styling for improved readability

---

package.json
src/map/ChartMarker.tsx
src/map/DonutMarker.tsx
src/plots/PiePlot.tsx
src/stories/ChartMarkers.stories.tsx
src/stories/DonutMarkers.stories.tsx
src/stories/api/getMarkersFromFixtureData.tsx

Question for reviewers: is the mouse pointer behaviour on the standalone markers what we want? I guess it is just the default behaviour because I don't think we've done anything special? Update: now I've done the chart markers too, the mouse pointer behaviour is completely different for that! It would be good if there was no special mouse pointer behaviour.  Suggestions welcome!
Also are we happy with the dangerous setting of inner HTML?
I think the UX people are not going to be happy with the cumulative donut markers, but we will cross that bridge when we come to it...

FSM marker-related work

---

package.json
src/plots/PlotlyPlot.tsx
src/plots/ScatterPlot.tsx
src/stories/plots/ScatterPlot.stories.tsx

This is required for resolving https://github.com/VEuPathDB/web-eda/issues/1487. Relevant PR will be made at web-eda too (https://github.com/VEuPathDB/web-eda/pull/1494). Screenshots can be found the corresponding web-eda PR.

marker opacity for scatter plot

---

package.json
src/plots/MosaicPlot.tsx
src/stories/plots/MosaicPlot.stories.tsx
src/utils/axis-tick-label-ellipsis.ts

Works toward https://github.com/VEuPathDB/web-eda/issues/617 and https://github.com/VEuPathDB/web-components/issues/427

Mosaic elbow labels

---

package.json
src/plots/ScatterPlot.tsx
src/stories/plots/ScatterPlot.stories.tsx
yarn.lock

Following @bobular's suggestion on https://github.com/VEuPathDB/web-eda/pull/1494#issuecomment-1357876861, the prop name is changed to markerBodyOpacity.

change prop name

---

package.json
src/plots/PlotlyPlot.tsx
src/stories/plots/MosaicPlot.stories.tsx
yarn.lock

This will address https://github.com/VEuPathDB/web-eda/issues/1377. Since there is another mosaic work by Connor, https://github.com/VEuPathDB/web-components/pull/418, this is branched out from [mosaic-elbow-labels](https://github.com/VEuPathDB/web-components/tree/mosaic-elbow-labels) to minimize conflicts and accommodate new layouts. Thus, this PR will be finalized when https://github.com/VEuPathDB/web-components/pull/418 is done.
Now both X and Y axes have ellipsis. For this, the max length of X-axis string is set to 80. Also, a story is made for testing. Here is a screenshot.

Mosaic long axis title

---

package.json
src/plots/MosaicPlot.tsx

This will address https://github.com/VEuPathDB/web-components/issues/428. I already discussed with Danica and she confirmed my mockup was good. https://github.com/VEuPathDB/web-components/issues/428#issuecomment-1379798117. Screenshots can be found at the ticket.

mosaic unified tooltip

---

package.json
src/plots/FacetedPlot.tsx
src/stories/plots/Barplot.stories.tsx

Fixes https://github.com/VEuPathDB/web-components/issues/339

Center faceted plot in fullscreen modal

---

package.json
src/plots/LinePlot.tsx
src/plots/PlotlyPlot.tsx
src/stories/plots/LinePlot.stories.tsx

Works alongside https://github.com/VEuPathDB/web-eda/pull/1581 to resolve https://github.com/VEuPathDB/EdaNewIssues/issues/547
See https://github.com/VEuPathDB/web-eda/pull/1581#issue-1558685624 for details on this work.

Change hovermode for line plot markers
